[tool.poetry]
name = "mnist-gan"
version = "0.1.0"
description = "A template repository for GANs"
authors = ["Harish Rajagopal <harish.rajagopals@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.8"
tensorflow = "^2.3.1"
tqdm = "^4.54.1"
PyYAML = "^5.3.1"

[tool.poetry.dev-dependencies]
pre-commit = "^2.9.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.black]
line-length = 79
